### ISSUE TITLE
table parsing does not allow trailing commas

### ISSUE THREAD

**Issue by 1e1001** [Bogdanp/racket-lua#5]
in lua
```
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
> return {1,2,}
table: 0x1025c10
```
vs. in racket
```
Welcome to Racket v8.9 [cs].
> return {1,2,}
; readline-input::13: expected expression but found } [,bt for context]
```
i haven't looked around the code much but i think the issue is in the implementation of [`parse-fields`](https://github.com/Bogdanp/racket-lua/blob/d8ab6697771a5f2ce8967d41f8bbe3e36b3c3f63/lua-lib/lang/parser.rkt#L446-L459), it doesn't seem to be used anywhere except `parse-table`, so it could probably be changed to something along the lines of:
- exit if there's a `}`
- parse an item
- exit if there's a `}`
- skip a `,` or `;`
- repeat

**Comment by Bogdanp** [comment]
Thanks for the report!
